<?php

declare(strict_types=1);

namespace App\Infrastructure\Cpm;

use App\Domain\Pokemon\Model\DexNumber;
use App\Domain\Pvp\Model\MegaLevel;
use App\Domain\Pvp\Model\MegaLevelEffects;
use App\Domain\Pvp\Port\MegaLevelTable;
use App\Infrastructure\Json\JsonPath;
use App\Infrastructure\Json\JsonValue;

/**
 * Reads the Mega Level table generated by `pogo:data:build`.
 */
final class JsonFileMegaLevelTable implements MegaLevelTable
{
    /** @var array<string, int>|null */
    private ?array $additional = null;

    /** @var array<string, int> */
    private array $cooldown = [];

    /** @var array<string, int> */
    private array $candy = [];

    /** @var array<string, float> */
    private array $movePower = [];

    /** @var array<string, int> */
    private array $maxByDex = [];

    public function __construct(
        private readonly string $file,
    ) {}

    #[\Override]
    public function effectsAt(MegaLevel $level): MegaLevelEffects
    {
        $this->load();
        $key = (string) $level->value;

        return new MegaLevelEffects(
            additionalLevels: $this->additional[$key] ?? 0,
            cooldownDays: $this->cooldown[$key] ?? 0,
            extraCandy: $this->candy[$key] ?? 0,
            movePowerMultiplier: $this->movePower[$key] ?? 1.0,
        );
    }

    #[\Override]
    public function maxLevelFor(DexNumber $dex): ?MegaLevel
    {
        $this->load();
        $max = $this->maxByDex[(string) $dex->value] ?? null;

        return null === $max || $max < MegaLevel::MIN ? null : new MegaLevel(min($max, MegaLevel::MAX));
    }

    private function load(): void
    {
        if (null !== $this->additional) {
            return;
        }

        if (!is_file($this->file)) {
            throw new \RuntimeException(\sprintf(
                'Mega level file "%s" is missing; run "bin/console pogo:data:build".',
                $this->file,
            ));
        }

        $this->additional = $this->intMapAt('additionalLevels');
        $this->cooldown = $this->intMapAt('cooldownDays');
        $this->candy = $this->intMapAt('extraCandy');
        $this->movePower = $this->floatMapAt('movePowerMultipliers');
        $this->maxByDex = $this->intMapAt('maxLevelByDex');
    }

    /**
     * @return array<string, float>
     */
    private function floatMapAt(string $key): array
    {
        return (
            JsonPath::floatMapAt(
                json_decode((string) file_get_contents($this->file), true, flags: \JSON_THROW_ON_ERROR),
                $key,
            ) ?? []
        );
    }

    /**
     * @return array<string, int>
     */
    private function intMapAt(string $key): array
    {
        $source = JsonPath::arrayAt(
            json_decode((string) file_get_contents($this->file), true, flags: \JSON_THROW_ON_ERROR),
            $key,
        );

        $map = [];

        foreach (array_map(JsonValue::asInt(...), $source ?? []) as $entryKey => $value) {
            if (null === $value) {
                continue;
            }

            $map[(string) $entryKey] = $value;
        }

        return $map;
    }
}
