<?php

declare(strict_types=1);

namespace App\Infrastructure\Cpm;

use App\Domain\Pvp\Model\PokemonLevel;
use App\Domain\Pvp\Port\CpMultiplierTable;
use App\Infrastructure\Json\JsonPath;

/**
 * Reads the CPM table generated by `pogo:data:build`, half levels already interpolated.
 */
final class JsonFileCpMultiplierTable implements CpMultiplierTable
{
    /** @var array<string, float>|null */
    private ?array $multipliers = null;

    public function __construct(
        private readonly string $file,
    ) {}

    #[\Override]
    public function multiplierFor(PokemonLevel $level): float
    {
        $this->load();

        $multiplier = $this->multipliers[(string) $level] ?? null;

        if (null === $multiplier) {
            throw new \RuntimeException(\sprintf(
                'No CP multiplier for level %s; rebuild with "bin/console pogo:data:build".',
                $level,
            ));
        }

        return $multiplier;
    }

    private function load(): void
    {
        if (null !== $this->multipliers) {
            return;
        }

        if (!is_file($this->file)) {
            throw new \RuntimeException(\sprintf(
                'CP multiplier file "%s" is missing; run "bin/console pogo:data:build".',
                $this->file,
            ));
        }

        $multipliers = JsonPath::floatMapAt(
            json_decode((string) file_get_contents($this->file), true, flags: \JSON_THROW_ON_ERROR),
            'multipliers',
        );

        if (null === $multipliers || [] === $multipliers) {
            throw new \RuntimeException(\sprintf('CP multiplier file "%s" is malformed.', $this->file));
        }

        $this->multipliers = $multipliers;
    }
}
