<?php

declare(strict_types=1);

namespace App\Infrastructure\Catalog;

use App\Domain\Pokemon\Model\DexNumber;
use App\Domain\Pokemon\Model\Species;
use App\Domain\Pokemon\Model\SpeciesId;
use App\Domain\Pokemon\Port\SpeciesCatalog;
use App\Infrastructure\Naming\LocalisedSpeciesNames;

/**
 * Reads the species file generated by `pogo:data:build`. No network at runtime:
 * names and base stats change only when the game does.
 */
final class JsonFileSpeciesCatalog implements SpeciesCatalog
{
    private ?SpeciesIndex $index = null;

    public function __construct(
        private readonly SpeciesFileReader $reader,
        private readonly NameNormalizer $normalizer,
        private readonly LocalisedSpeciesNames $names,
    ) {}

    #[\Override]
    public function search(string $identifier): array
    {
        $needle = $this->normalizer->normalize($identifier);

        if ('' === $needle) {
            return [];
        }

        return $this->preferBaseForm($this->candidatesFor($identifier, $needle));
    }

    #[\Override]
    public function find(SpeciesId $id): ?Species
    {
        return $this->index()->byIdentity($id);
    }

    #[\Override]
    public function megaFormsOf(DexNumber $dex): array
    {
        return array_values(array_filter(
            $this->index()->byDex($dex->value),
            static fn(Species $species): bool => $species->isMega(),
        ));
    }

    #[\Override]
    public function baseFormOf(DexNumber $dex): ?Species
    {
        foreach ($this->index()->byDex($dex->value) as $species) {
            if ($species->isBaseForm()) {
                return $species;
            }
        }

        return null;
    }

    /**
     * @return list<Species>
     */
    private function candidatesFor(string $identifier, string $needle): array
    {
        $index = $this->index();

        if (1 === preg_match('#^\d+$#', $needle)) {
            return $index->byDex((int) $needle);
        }

        $byId = $index->byId($identifier);

        if (null !== $byId) {
            return [$byId];
        }

        $exact = $index->byExactName($needle);

        // No exact hit: offer what the input could have meant rather than "not found".
        return [] !== $exact ? $exact : $index->byNamePrefix($needle);
    }

    /**
     * "94" and "Ectoplasma" both cover Gengar, Mega Gengar and Shadow Gengar; "Raichu
     * (d'Alola)" covers the Alolan form and its shadow. In both cases the user means the
     * one without a mega or shadow segment — those are reached through their own flag.
     *
     * @param list<Species> $candidates
     *
     * @return list<Species>
     */
    private function preferBaseForm(array $candidates): array
    {
        $plain = array_values(array_filter($candidates, static fn(Species $s): bool => 0 === $s->flagFormCount()));

        return [] !== $plain ? $plain : $candidates;
    }

    private function index(): SpeciesIndex
    {
        return $this->index ??= new SpeciesIndex($this->reader->read(), $this->normalizer, $this->names);
    }
}
