<?php

declare(strict_types=1);

namespace App\Infrastructure\Catalog;

use App\Domain\Pokemon\Model\Move;
use App\Domain\Pokemon\Model\MoveId;
use App\Domain\Pokemon\Port\MoveCatalog;
use App\Infrastructure\Json\JsonPath;
use App\Infrastructure\Json\JsonValue;

/**
 * Reads the move file generated by `pogo:data:build`.
 */
final class JsonFileMoveCatalog implements MoveCatalog
{
    /** @var array<string, Move>|null */
    private ?array $moves = null;

    public function __construct(
        private readonly string $file,
    ) {}

    #[\Override]
    public function find(MoveId $id): ?Move
    {
        $this->load();

        return $this->moves[$id->value] ?? null;
    }

    private function load(): void
    {
        if (null !== $this->moves) {
            return;
        }

        if (!is_file($this->file)) {
            throw new \RuntimeException(\sprintf(
                'Move file "%s" is missing; run "bin/console pogo:data:build".',
                $this->file,
            ));
        }

        $this->moves = [];

        foreach ($this->entries() as $entry) {
            $id = JsonValue::asString($entry['id'] ?? null);

            if (null === $id) {
                continue;
            }

            $this->moves[$id] = new Move(
                new MoveId($id),
                JsonValue::asInt($entry['power'] ?? null) ?? 0,
                JsonValue::asInt($entry['energy'] ?? null) ?? 0,
                true === ($entry['mega'] ?? false),
            );
        }
    }

    /**
     * @return list<array<array-key, mixed>>
     */
    private function entries(): array
    {
        return JsonPath::arrayListAt(
            json_decode((string) file_get_contents($this->file), true, flags: \JSON_THROW_ON_ERROR),
            'moves',
        );
    }
}
